{% set name = "implicit" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/benfred/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1f09519a3d6b4b250b135e23bcaeaf6bbc5b70f2a14fd8ef6c5882032d2c6a99

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                    # [not win]
  host:
    - python
    - pip
    - wheel
    - cython 0.29
    - scipy 1.10
    - scikit-build 0.15
  run:
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - python
    - tqdm >=4.27
    - _openmp_mutex           # [linux]
    - llvm-openmp             # [osx]

test:
  requires:
    - pip
  imports:
    - implicit
    - implicit.cpu._als
  commands:
    - pip check

about:
  home: https://github.com/benfred/implicit/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast Python Collaborative Filtering for Implicit Datasets.
  description: |
    This project provides fast Python implementations of the algorithms
    described in the paper Collaborative Filtering for Implicit Feedback
    Datasets and in Applications of the Conjugate Gradient Method
    for Implicit Feedback Collaborative Filtering
  doc_url: https://implicit.readthedocs.io/
  dev_url: https://github.com/benfred/implicit/

extra:
  recipe-maintainers:
    - rth
    - benfred
    - sumit0190
