{% set name = "implicit" %}
{% set version = "0.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/benfred/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7a15154156943cbf4b79bf99a352990b485175ec9cbb9b14774b6fa8d4941ca4

build:
  number: 0
  script_env:
    - CMAKE_GENERATOR=Ninja
  script: python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # CMake 4.x dropped compatibility with policy versions below 3.5, so projects
    # declaring cmake_minimum_required(VERSION 3.1), and build was failed.
    - cmake >=3.18,<4
    - ninja-base
  host:
    - pip
    - python
    - wheel
    - setuptools >=42
    - cython >=0.24
    - scikit-build >=0.13.1
    - scipy >=0.16
    - numpy {{ numpy }}
  run:
    - python
    - numpy >=1.17.0
    - scipy >=0.16
    - tqdm >=4.27
    - threadpoolctl
    # OPENMP -> https://github.com/benfred/implicit/blob/v0.7.2/CMakeLists.txt#L9
    - _openmp_mutex           # [linux]
    - llvm-openmp             # [osx]

{% set ignore_tests = "" %}
# Issue: https://github.com/benfred/implicit/issues/740
# E   ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
{% set ignore_tests = " --ignore=tests/knn_test.py" %}  # [win]
test:
  source_files:
    - tests
  imports:
    - implicit
    - implicit.cpu._als
  commands:
    - pip check
    - python -c "import implicit; print(implicit.__version__)"
    - pytest -v tests {{ ignore_tests }}
  requires:
    - pip
    - pytest
    # https://github.com/benfred/implicit/issues/726
    - scipy <1.15

about:
  home: https://github.com/benfred/implicit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast Python Collaborative Filtering for Implicit Datasets.
  description: |
    Fast Python Collaborative Filtering for Implicit Datasets.
    This project provides fast Python implementationsof several different
    popular recommendation algorithms for implicit feedback datasets:
      Alternating Least Squares as described in the papers Collaborative Filtering for Implicit Feedback Datasets and
      Applications of the Conjugate Gradient Method for Implicit Feedback Collaborative Filtering.
      Bayesian Personalized Ranking.
      Logistic Matrix Factorization
      Item-Item Nearest Neighbour models using Cosine, TFIDF or BM25 as a distance metric.
    All models have multi-threaded training routines, using Cython and
    OpenMP to fit the models in parallel among all available CPU cores.
    In addition, the ALS and BPR models both have custom CUDA kernels - enabling fitting on compatible GPU's.
     Approximate nearest neighbours libraries such as Annoy, NMSLIB and Faiss can also be used by Implicit
     to speed up making recommendations.
  doc_url: https://implicit.readthedocs.io
  dev_url: https://github.com/benfred/implicit


extra:
  recipe-maintainers:
    - rth
    - benfred
  skip-lints:
    - host_section_needs_exact_pinnings