{% set name = "implicit" %}
{% set version = "0.3.2" %}
{% set sha256 = "a177b706570255b590ade1c88efa3111799505160ae8b00c1e9f58c6387f5003" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: True  # [win and py27]

requirements:
  build:
    - python
    - pip
    - toolchain
    - cython >=0.24
    - gcc  # [unix]
    - numpy 1.11.*
    # implicit cimports BLAS from scipy
    - scipy 0.18.*
  run:
    - python
    - libgcc  # [unix]
    - numpy >=1.11  # [win and py36]
    - scipy >=0.18

test:
  imports:
    - implicit
    - implicit._als

about:
  home: http://github.com/benfred/implicit/
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: 'Fast Python Collaborative Filtering for Implicit Datasets.'
  description: |
      This project provides fast Python implementations of the algorithms
      described in the paper Collaborative Filtering for Implicit Feedback
      Datasets and in Applications of the Conjugate Gradient Method
      for Implicit Feedback Collaborative Filtering
  doc_url: http://implicit.readthedocs.io/
  dev_url: http://github.com/benfred/implicit/

extra:
  recipe-maintainers:
    - rth
    - benfred
