travis:
  secure:
    BINSTAR_TOKEN: cFWCgWZPuqPcnC8KMPCib4eaOMpQ97qBsVd5eYcaDjuvbt3EcZeXs/z34hu1pvRkyosiqc3dcH7HAtScWb+gQGuSI+gna1aZuSkQdxZOY0hxUYYaVtBn3Am0OOsjaaP088sc7KcT1JRXYLOYpZQ71ABpuXbtKAxHeB5ldsIC9jGX4k2i4vYhOZyfYJvmQ6ikyxItikIQKEaA13Peareky5q41LYVz5ued9fgEmBvI7UcL5pPQcCpMxUHJIgq/MZY0ixzYxMC1597Jx7fzL+NztEZrDGgtTs+pA/GkIzkohYdnuJa5sQvxNYsviDxNs5tYngpc6dXGiQL2DSxxsMmuVTEMZ/o1NtfZA+2eAlUVYl7utZgT4VHdD9HTfbQwDtrhb+4oQItS6Z1qfRc/Ofoe3Vx23m1ynGwR1qwC7cr4jPWorHKlmg/UBGBbEPDIsR1v/gIdn6WQztnol30Y4jhmfAOMGBPNpEG+63TlPmwqmUKgysIYkzdzZeAd1Q94H177qDI08sld4HSQrCb2/11A1n3KBlvDBk3Qb9CjrM/ihrPb+h5ljrHSU/CVAsG2qHxruqEbYISeD3LswnoeME+TfEqyPvyUGVn6VJdHeeIAv7fIjA8hfB8z0ii0Hj6+ZigtiQclU9LFgHCAX2RjGbO8HBUb9KeajXFzEjJ5Qq0zn8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
